import type { Project, Objective, Initiative } from '../types';

export const demoProjects: Omit<Project, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'App Mobile de Fitness',
    description: 'Desenvolvimento de aplicativo mobile para acompanhamento de treinos e nutrição',
    category: 'work',
    status: 'active',
    priority: 'high',
    progress: 65,
    startDate: new Date('2024-01-15'),
    targetEndDate: new Date('2024-06-30'),
    objectiveIds: [],
    milestones: [
      {
        id: 'm1',
        title: 'Design UI/UX Completo',
        description: 'Finalizar todos os mockups e fluxos de usuário',
        date: new Date('2024-02-28'),
        projectId: '',
        completed: true,
        category: 'work',
      },
      {
        id: 'm2',
        title: 'MVP Backend',
        description: 'API REST com autenticação e CRUD básico',
        date: new Date('2024-03-30'),
        projectId: '',
        completed: true,
        category: 'work',
      },
      {
        id: 'm3',
        title: 'Beta Testing',
        description: 'Lançar versão beta para 50 usuários',
        date: new Date('2024-05-15'),
        projectId: '',
        completed: false,
        category: 'work',
      },
    ],
    redFlags: [
      {
        id: 'rf1',
        title: 'Atraso no desenvolvimento iOS',
        description: 'Equipe reduzida, risco de não entregar no prazo',
        severity: 'high',
        projectId: '',
        createdAt: new Date('2024-03-10'),
        resolved: false,
      },
    ],
    tags: ['mobile', 'react-native', 'fitness'],
  },
  {
    title: 'Preparação para Maratona',
    description: 'Programa de treinamento para correr minha primeira maratona',
    category: 'training',
    status: 'active',
    priority: 'high',
    progress: 45,
    startDate: new Date('2024-02-01'),
    targetEndDate: new Date('2024-11-10'),
    objectiveIds: [],
    milestones: [
      {
        id: 'm4',
        title: 'Completar 21K',
        description: 'Primeira meia maratona oficial',
        date: new Date('2024-06-15'),
        projectId: '',
        completed: false,
        category: 'training',
      },
      {
        id: 'm5',
        title: 'Atingir 80km/semana',
        description: 'Base de quilometragem semanal',
        date: new Date('2024-08-30'),
        projectId: '',
        completed: false,
        category: 'training',
      },
    ],
    redFlags: [],
    tags: ['corrida', 'maratona', 'saúde'],
  },
  {
    title: 'EP de Jazz Fusion',
    description: 'Gravação de EP com 5 músicas originais de jazz fusion',
    category: 'music',
    status: 'active',
    priority: 'medium',
    progress: 30,
    startDate: new Date('2024-03-01'),
    targetEndDate: new Date('2024-12-31'),
    objectiveIds: [],
    milestones: [
      {
        id: 'm6',
        title: 'Composições Finalizadas',
        description: 'Todas as 5 músicas compostas e arranjos prontos',
        date: new Date('2024-05-30'),
        projectId: '',
        completed: false,
        category: 'music',
      },
      {
        id: 'm7',
        title: 'Gravação do EP',
        description: 'Sessões de gravação em estúdio',
        date: new Date('2024-09-15'),
        projectId: '',
        completed: false,
        category: 'music',
      },
    ],
    redFlags: [],
    tags: ['jazz', 'composição', 'gravação'],
  },
];

export const demoObjectives: Omit<Objective, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Crescer a base de usuários em 150%',
    description: 'Aumentar usuários ativos mensais de 1.000 para 2.500',
    category: 'work',
    quarter: 'Q2 2024',
    keyResults: [
      {
        id: 'kr1',
        description: 'Atingir 2.500 usuários ativos mensais',
        target: 2500,
        current: 1450,
        unit: 'usuários',
        status: 'in-progress',
      },
      {
        id: 'kr2',
        description: 'Alcançar taxa de retenção de 70%',
        target: 70,
        current: 55,
        unit: '%',
        status: 'in-progress',
      },
      {
        id: 'kr3',
        description: 'Obter NPS acima de 50',
        target: 50,
        current: 42,
        unit: 'pontos',
        status: 'at-risk',
      },
    ],
    status: 'in-progress',
    progress: 58,
  },
  {
    title: 'Melhorar performance física',
    description: 'Atingir melhores marcas pessoais em corrida e força',
    category: 'training',
    quarter: 'Q2 2024',
    keyResults: [
      {
        id: 'kr4',
        description: 'Correr 10K em menos de 45 minutos',
        target: 45,
        current: 48,
        unit: 'min',
        status: 'in-progress',
      },
      {
        id: 'kr5',
        description: 'Completar 180km de corrida no mês',
        target: 180,
        current: 165,
        unit: 'km',
        status: 'in-progress',
      },
    ],
    status: 'in-progress',
    progress: 75,
  },
  {
    title: 'Lançar primeira obra musical completa',
    description: 'Gravar e publicar EP em plataformas de streaming',
    category: 'music',
    quarter: 'Q4 2024',
    keyResults: [
      {
        id: 'kr6',
        description: 'Compor 5 músicas originais',
        target: 5,
        current: 3,
        unit: 'músicas',
        status: 'in-progress',
      },
      {
        id: 'kr7',
        description: 'Atingir 10.000 streams no Spotify',
        target: 10000,
        current: 0,
        unit: 'streams',
        status: 'not-started',
      },
    ],
    status: 'in-progress',
    progress: 40,
  },
];

export const demoInitiatives: Omit<Initiative, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Podcast sobre Tecnologia',
    description: 'Criar podcast semanal sobre desenvolvimento de software e inovação',
    category: 'work',
    status: 'idea',
    priority: 'medium',
    estimatedEffort: 'Médio',
    potentialImpact: 'Alto',
    notes: 'Pesquisar equipamentos necessários e formato ideal. Avaliar parceria com outros devs.',
  },
  {
    title: 'Certificação AWS Solutions Architect',
    description: 'Estudar e obter certificação AWS para arquitetura de soluções',
    category: 'learning',
    status: 'planned',
    priority: 'high',
    estimatedEffort: 'Grande',
    potentialImpact: 'Alto',
    notes: 'Já comprei o curso na Udemy. Meta: passar na prova até julho.',
  },
  {
    title: 'Aulas de Piano Jazz',
    description: 'Retomar aulas de piano com foco em improvisação jazz',
    category: 'music',
    status: 'idea',
    priority: 'low',
    estimatedEffort: 'Médio',
    potentialImpact: 'Médio',
    notes: 'Avaliar professores disponíveis na região. Orçamento: R$ 200-300/mês',
  },
  {
    title: 'Blog Pessoal',
    description: 'Criar blog para compartilhar aprendizados sobre desenvolvimento',
    category: 'personal',
    status: 'in-progress',
    priority: 'medium',
    estimatedEffort: 'Pequeno',
    potentialImpact: 'Médio',
    notes: 'Domínio já comprado. Escolher entre Next.js ou Astro.',
  },
];
